server:
  port: 8001
logging:
  level:
    com.iot.app: trace

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5421/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  cloud:
    discovery:
      client:
        simple:
          instances:
            communicationServer[0].uri: http://localhost:8002
            statusManager[0].uri: http://localhost:8004

eureka:
  instance:
    hostname: localhost
  client:
    enabled: false