server:
  port: 8004
logging:
  level:
    com.example: trace

spring:
  data:
    mongodb:
      host: localhost
      port: 27777
      database: IOT
      username: iot
      password: iot_password