server:
  port: 8002
logging:
  level:
    com.example: trace

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            statusManager[0].uri: http://localhost:8004

eureka:
  instance:
    hostname: localhost
  client:
    enabled: false