server:
  port: 8002
logging:
  level:
    com.iot: debug

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            statusManager[0].uri: http://localhost:8004
  data:
    mongodb:
      host: localhost
      port: 27777
      database: IOT
      username: iot
      password: iot_password

eureka:
  instance:
    hostname: localhost
  client:
    enabled: false
